io:
  muenchendigital:
    digiwf:
      ocecosmos:
        url: '<oce-cosmos-url>'
        defaults:
          applicationName:
          templateName:
          jobType:
          debtor:
          printJob: true
          mailJob: false
          archiveJob: false
          hostName:
          userId:
          dataType:
        oauth-client:
          username:
          password:
          clientId:
          accessTokenUri: ${io.muenchendigital.digiwf.ocecosmos.url}/cosmos-webauth/oauth/token
          clientSecret:
          scope:

spring:
  cloud:
    stream:
      bindings:
        functionRouter-in-0:
          destination: <topic>
          group: <groupId>
        sendCorrelateMessage-out-0:
          destination: <topic>
        sendMessage-out-0:
          destination: <topic>
      kafka:
        binder:
          brokers: <brokerUrl>
  kafka:
    ssl:
      key-store-location: ''
      key-store-password: ''
      trust-store-location: ''
      trust-store-password: ''
